feat: inquisitor parser
Date test failed because the format being parsed is different:
AssertionError: '2016-12-12T16:07:20.000Z' ==
'2016-12-12T16:07:20+00:00'

Again, didn’t want to cheat.

Image didn’t show in preview, but otherwise it looks good!